name: go

on:
  push:
    branches:
      - flaky-tests
    tags:
  pull_request:

# TODO(bwplotka): Add tests here.
jobs:
  e2e:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    name: Thanos end-to-end tests
    env:
      GOBIN: /tmp/.bin
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Go.
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.x

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/.cache/golangci-lint
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: Run e2e docker-based tests
        run: make test-e2e GH_PARALLEL=4 GH_INDEX=3
